const DAY = 86_400_000;
const dateInZone = (value, timeZone) => { const p = Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone, year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(value).filter(x => x.type !== 'literal').map(x => [x.type, x.value])); return `${p.year}-${p.month}-${p.day}`; };
export function todayWindow(now = new Date(), timeZone = 'America/New_York') { return { mode: 'today', windowStart: new Date(now.getTime() - DAY), windowEnd: new Date(now), start: dateInZone(new Date(now.getTime() - DAY), timeZone), end: dateInZone(now, timeZone) }; }
export function calendarRange(now, days, timeZone = 'America/New_York') { const end = dateInZone(now, timeZone); const start = new Date(`${end}T12:00:00Z`); start.setUTCDate(start.getUTCDate() - (days - 1)); return { mode: 'calendar', start: start.toISOString().slice(0, 10), end }; }
export function calendarDaysForFilters(filters, timeZone = 'America/New_York') { const start = filters.windowStart ? dateInZone(filters.windowStart, timeZone) : filters.start; const end = filters.windowEnd ? dateInZone(filters.windowEnd, timeZone) : filters.end; const rows = []; for (let d = new Date(`${start}T12:00:00Z`), last = new Date(`${end}T12:00:00Z`); d <= last; d.setUTCDate(d.getUTCDate() + 1)) rows.push(d.toISOString().slice(0, 10)); return rows; }
export function statusRowsForFilters(days, filters, timeZone = 'America/New_York') { const byDate = new Map((days || []).map(row => [row.date, row])); return calendarDaysForFilters(filters, timeZone).reverse().map(date => byDate.get(date) || { date, status: 'gray', label: '未執行', summary: '此紐約日沒有掃描紀錄。', issues: [] }); }
export function statusTooltip(row) { return [row.summary, ...(row.issues || [])].filter(Boolean).join('\n'); }
export function validStatusRow(row) { return Boolean(row && /^\d{4}-\d{2}-\d{2}$/.test(row.date) && ['green', 'yellow', 'red'].includes(row.status) && typeof row.label === 'string' && typeof row.summary === 'string' && Array.isArray(row.issues)); }
export function renderScanStatus(container, rows) { const doc = container.ownerDocument; doc.querySelectorAll('[data-scan-status-tooltip]').forEach(tooltip => tooltip.remove()); container.replaceChildren(); for (const [index, row] of rows.entries()) { const tr = doc.createElement('tr'); const dot = doc.createElement('span'); dot.className = `status-dot ${row.status}`; dot.tabIndex = 0; dot.setAttribute('role', 'img'); const detail = statusTooltip(row); const detailId = `scan-status-detail-${index}`; dot.setAttribute('aria-label', `${row.label}: ${detail}`); dot.setAttribute('aria-describedby', detailId); dot.title = detail; const tooltip = doc.createElement('span'); tooltip.id = detailId; tooltip.className = 'status-detail'; tooltip.dataset.scanStatusTooltip = ''; tooltip.setAttribute('role', 'tooltip'); tooltip.textContent = detail; tooltip.hidden = true; doc.body.append(tooltip); const place = () => { tooltip.hidden = false; const dotBox = dot.getBoundingClientRect(); const viewportWidth = doc.defaultView.innerWidth; tooltip.style.left = `${Math.max(8, Math.min(dotBox.left, viewportWidth - Math.min(360, viewportWidth * .7) - 8))}px`; tooltip.style.top = `${dotBox.bottom + 8}px`; const detailBox = tooltip.getBoundingClientRect(); if (detailBox.bottom > doc.defaultView.innerHeight && dotBox.top - detailBox.height - 8 >= 8) tooltip.style.top = `${dotBox.top - detailBox.height - 8}px`; }; const hide = () => { tooltip.hidden = true; }; dot.addEventListener('mouseenter', place); dot.addEventListener('mouseleave', hide); dot.addEventListener('focus', place); dot.addEventListener('blur', hide); const status = doc.createElement('td'); status.className = 'status-cell'; status.append(dot, doc.createTextNode(` ${row.label}`)); const value = x => x == null ? '—' : String(x); tr.innerHTML = `<td>${row.date}</td>`; tr.append(status); for (const item of [`${value(row.scannedPortals)} 掃描 / ${value(row.found)} 發現`, `${value(row.published)} 發布 / ${value(row.normalPending)} 待處理`, `${value(row.candidateExceptions)} JD / ${value(row.sourceExceptions)} 來源`]) { const td = doc.createElement('td'); td.textContent = item; tr.append(td); } container.append(tr); } }
